id: I0294E8C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:55:51+00:00'
last_modified: '2022-06-08T01:41:03.072310+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD127771
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6D8D:
      image_group_id: I1KG17047
      title: ''
      total_pages: 252
      order: 1
      base_file: 6D8D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
