id: P004523
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD127771
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  volumes:
    e25bffe1c67a412d88f33a10ea39af08:
      image_group_id: I1KG17047
      title: ''
      volume_number: 1
      total_pages: 252
