id: P004523
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:29:32.551619
source_metadata:
  id: bdr:W1PD127771
  title: བར་དོ་ཐོས་གྲོལ་ཆེན་མོ།
  author: ''
  volumes:
    e25bffe1c67a412d88f33a10ea39af08:
      image_group_id: I1KG17047
      title: ''
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
